/** @format */

import React, { useState, useEffect } from 'react';
import EventPageCard from './EventPageCard';

//this component, as well as its child eventPageCard, are responsible for displaying data about an event on a seperate page with a unique url.
const Event = (props) => {
	//this grabs the parameter from the url with the name of the event.
	const {
		params: { eventName },
	} = props.match;

	//create some state to hold data about the event the user is viewing
	const [eventState, setEventState] = useState({});
	const [coords, setCoords] = useState({
		lat: '',
		lng: '',
	});
	const [pictureArray, setPictureArray] = useState([]);

	//here we define our fetch call to the backend.
	const getEvent = async (name) => {
		//name will be formatted to remove dashes on server before mongoDB search
		const event = await fetch(
			`http://localhost:3001/api/events/event/${name}`
		).then(async (result) => {
			const newData = await result.json();
			console.log(newData.name);
			console.log(eventName);
			console.log(newData);
			
			//here we double check that the event name in the arguement to getEvent and the event returned from the server are the same before setting to state
			if (newData.name === eventName.split('-').join(' ')) {
				handleSetEventState(newData);
			}
			// return newData
		});
	};
	// destructure eventState object.
	const {
		name,
		type,
		// startDate,
		// startTime,
		// endDate,
		// endTime,
		address,
		city,
		state,
		postal,
		description,
		// links,
		pictures,
		// files,
		startDateTime,
	} = eventState;

	//handler for setting coordinates state.
	const handleSetCoords = (newCoords) => {
		setCoords(newCoords);
	};

	//handler for setting event state.
	const handleSetEventState = (eventState) => {
		setEventState(eventState);
	};

	//create a variable to hold the new array generated by parsing through the pictures string.
	let formattedPictureArray;
	if (pictures) {
		formattedPictureArray = pictures
			.replace(/\n/g, ' ')
			.split(' ')
			.filter((picture) => picture !== '');
	}

	//TODO refactor getcoords out of component
	useEffect(() => {
		//get the event data associated with the url from mongo db and use it to set local
		getEvent(eventName);
	}, [eventName]);

	useEffect(() => {
		//set pictureArr created above to state.
		setPictureArray(formattedPictureArray);
	}, [eventState.pictures]);

	return (
		<div className='m-5'>
			<EventPageCard
				eventState={eventState}
				coords={coords}
				test={'this is a test'}
				handleSetCoords={handleSetCoords}
				pictureArray={pictureArray}
			/>
			<div id='bottom-boundary'></div>
		</div>
	);
};

export default Event;
